# Generated by Django 4.1 on 2022-09-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='acierto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
