# Generated by Django 4.1 on 2022-09-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_prueba_aciertoprueba_alter_preguntas_acierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='aciertotema',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
